Repository UNIZAR-30226-2025-07/frontend, pull requests merged in 2025-05, with the labels that each got.

#117 arreglar tres bugs
  src/components/ConfigurationItem.jsx
  src/components/Navbar.astro
  src/pages/achievements.astro
  src/pages/createPG.astro
  src/pages/friends.astro
  src/pages/index.astro
Labels: bug

#128 Pausa y GameOver
  src/pages/gameOver.astro
  src/pages/pause.astro
Labels: enhancement

#135 arreglar bug footerLinks
  README.md
  src/components/PlayPrivateButton.jsx
  src/components/ReadyButton.jsx
  src/pages/index.astro
Labels: bug

#145 Tests de accesibilidad y seguridad
  .babelrc
  jest.config.cjs
  package.json
  src/__mocks__/astroMock.js
  src/__mocks__/components/NicknameInput.jsx
  src/__mocks__/fileMock.js
  tests/accesibility/AspectSelector.test.js
  tests/accesibility/PlayButton.test.js
  tests/accesibility/ReadyButton.test.js
  tests/jest.setup.js
  tests/security/xss-prevention.test.js
Labels: tests
