Repository UNIZAR-30226-2025-07/frontend, pull requests merged in 2025-03, with the labels that each got.

#27 pantalla de amigos y realizadas mejoras en la pantalla principal
  public/images/amigos/aceptar_amigos.png
  public/images/amigos/agregar_amigos.png
  public/images/amigos/eliminar_amigos.png
  public/images/volver.png
  src/components/AspectSelector.jsx
  src/components/Navbar.astro
  src/components/NicknameInput.astro
  src/components/friends/FriendItem.astro
  src/components/friends/FriendsList.astro
  src/pages/friends.astro
Labels: pantallas

#46 Crear cuenta [v 1.0]
  src/components/login/newCuenta.astro
Labels: feature

#53 Actualización pantalla amigos y pantalla tienda
  public/images/check_off.png
  src/components/ConfigurationItem.jsx
  src/components/StoreComponent.jsx
  src/pages/configuration.astro
  src/pages/store.astro
Labels: pantallas

#63 Logros y login modificado
  src/components/Navbar.astro
  src/components/achievements/AchieveItem.astro
  src/components/achievements/AchieveList.astro
  src/components/login/register.astro
  src/pages/achievements.astro
Labels: pantallas

#74 Integrar el juego con el frontend.
  src/assets/game/CanvasPool-Cl5tGF1K.js
  src/assets/game/SharedSystems-D1WwNreb.js
  src/assets/game/WebGLRenderer-CjrJgrhT.js
  src/assets/game/WebGPURenderer-BrKoAzM_.js
  src/assets/game/browserAll-B2IPZxaV.js
  src/assets/game/colorToUniform-C2GHuDhf.js
  src/assets/game/game.js
  src/assets/game/webworkerAll-j6hBgcFt.js
  src/components/PlayButton.astro
  src/pages/game.astro
Labels: feature

#75 Tests y primera versión conexión frontend y backend
  package.json
  playwright.config.ts
  src/components/Navbar.astro
  src/components/NicknameInput.astro
  src/components/friends/FriendItem.tsx
  src/components/friends/FriendsList.astro
  src/components/login/newCuenta.astro
  src/components/login/register.astro
  src/pages/index.astro
  src/styles/friendItem.css
  src/utils/cookies.js
  tests/navigation.spec.ts
Labels: pantallas, tests

#77 Conexion BD Amigos
  src/components/friends/FriendItem.tsx
  src/components/friends/FriendsList.astro
  src/components/friendsRequests/RequestItem.astro
  src/components/friendsRequests/RequestList.astro
Labels: backend, pantallas

#78 Perfil, chat y mejoras estéticas
  public/images/amigos/chat.png
  public/images/amigos/partida_privada.png
  src/components/Navbar.astro
  src/components/PlayButton.astro
  src/components/chat/Chat.jsx
  src/components/friends/FriendsList.astro
  src/components/friendsRequests/RequestList.astro
  src/components/login/newCuenta.astro
  src/components/login/register.astro
  src/pages/friends.astro
  src/pages/index.astro
  src/pages/login.astro
  src/pages/newCuenta.astro
  src/pages/profile.astro
  src/pages/requests.astro
  src/styles/chat.css
Labels: backend, pantallas
